[package]
name = "thor-discord"
version = "0.1.0"
authors = ["dnery"]
edition = "2018"

[dependencies]
serenity = "0.9.0-rc.2"
tokio = "0.2"
log = "0.4"
kankyo = "0.3"
env_logger = "0.7"
rand = "0.7"
toml = "0.5"
